# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Access API
        run: |
          export BRANCH="$(echo ${GITHUB_REF#refs/heads/})"
          curl --request GET \
            --url https://api.github.com/repos/${{ github.repository }}/actions/runs \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            | jq -r -n '.workflow_runs[] | select(.head_branch==env.BRANCH and .status == "completed" and .conclusion == "success") | { head_branch, status, conclusion, head_commit }'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          declare start="$(jq --raw-output .commits[0].id "$GITHUB_EVENT_PATH")"
          declare end="$(jq --raw-output .commits[-1].id "$GITHUB_EVENT_PATH")"
          echo "Start: $start"
          echo "End: $end"
          if [[ "$start" == "$end" ]]; then
            echo "Only 1 commit"
          else
            echo "Multipe commits"
          fi
          echo "EVENT:"
          jq --raw-output . "$GITHUB_EVENT_PATH"
          echo "DIFF WITH START"
          git diff --name-only "${start:?}"^
          echo "DIFF WITH END"
          git diff --name-only "${end:?}"^
