name: Demo teardown

env:
  TENANT_NAMESPACE: aeto

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      display_name:
        description: "Demo display name"
        default: ""

jobs:
  teardown:
    name: Teardown
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/demo/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Teardown tenant
        run: |
          export DEMO_NAME="${GITHUB_REF/refs\/heads\/demo\//}"
          export DEMO_DISPLAY_NAME='${{ github.event.inputs.display_name }}'
          [[ "${DEMO_DISPLAY_NAME:-}" == '' ]] && DEMO_DISPLAY_NAME="${DEMO_NAME:?}"
          export TENANT_NAME="demo-${DEMO_NAME:?}"
          echo "${TENANT_NAME}"

          echo ./stack --dev tenant teardown \
            --tenant-name="${TENANT_NAME:?}" \
            --tenant-namespace="${TENANT_NAMESPACE:?}" \
